# -*- coding: utf-8 -*-
"""matplot_library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJe1PYlFEBrDNu3b0BP1jZ4WvC8TBGcn
"""

#regression
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=1,noise=10)

x

y

plt.scatter(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.show()

#classification
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=10000,n_features=5,n_classes=2,random_state=0)
plt.scatter(x[:,0],x[:,1],c=y)
plt.show()

x

y

#blobs
from sklearn.datasets import make_blobs
x,y=make_blobs(n_samples=1000,n_features=2,centers=3,random_state=0)
plt.scatter(x[:,0],x[:,1],c=y)
plt.show()

x

y



from sklearn.datasets import make_circles
x,y=make_circles(n_samples=1000,noise=0.03,random_state=0)
plt.scatter(x[:,0],x[:,1],c=y)
plt.show()

y

#moons
from sklearn.datasets import make_moons
x,y=make_moons(n_samples=1000,noise=0.03,random_state=0)
plt.scatter(x[:,0],x[:,1],c=y)
plt.show()

y